const PRODUCTS = [
  {
    "id": 1,
    "title": "Grand Theft Auto V",
    "category": "Action & Open World",
    "platform": "PC / PS5 / Xbox",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 18000,
    "original": 32000,
    "rating": 4.6,
    "color": "#7c3aed",
    "tag": "Featured",
    "image": "assets/images/game-01.jpg"
  },
  {
    "id": 2,
    "title": "The Legend of Zelda: Breath of the Wild",
    "category": "Action & Open World",
    "platform": "Nintendo Switch",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 30000,
    "original": 45000,
    "rating": 4.7,
    "color": "#15803d",
    "tag": "Featured",
    "image": "assets/images/game-02.jpg"
  },
  {
    "id": 3,
    "title": "Red Dead Redemption 2",
    "category": "Action & Open World",
    "platform": "PC / PS4 / Xbox",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 25000,
    "original": 40000,
    "rating": 4.8,
    "color": "#b45309",
    "tag": "Featured",
    "image": "assets/images/game-03.jpg"
  },
  {
    "id": 4,
    "title": "Elden Ring",
    "category": "Action & Open World",
    "platform": "PC / PS5 / Xbox",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 32000,
    "original": 50000,
    "rating": 4.9,
    "color": "#7f1d1d",
    "tag": "Featured",
    "image": "assets/images/game-04.jpg"
  },
  {
    "id": 5,
    "title": "God of War",
    "category": "Action & Open World",
    "platform": "PC / PS4 / PS5",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 28000,
    "original": 42000,
    "rating": 4.5,
    "color": "#334155",
    "tag": "Featured",
    "image": "assets/images/game-05.jpg"
  },
  {
    "id": 6,
    "title": "Marvel's Spider-Man",
    "category": "Action & Open World",
    "platform": "PC / PS4 / PS5",
    "genre": "Action & Open World",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 26000,
    "original": 40000,
    "rating": 4.6,
    "color": "#0369a1",
    "tag": "Featured",
    "image": "assets/images/game-06.jpg"
  },
  {
    "id": 7,
    "title": "The Witcher 3: Wild Hunt",
    "category": "Role-Playing Games (RPGs)",
    "platform": "PC / PS4 / PS5 / Xbox / Switch",
    "genre": "Role-Playing Games (RPGs)",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 18000,
    "original": 30000,
    "rating": 4.7,
    "color": "#166534",
    "tag": "Available",
    "image": "assets/images/game-07.jpg"
  },
  {
    "id": 8,
    "title": "Baldur's Gate 3",
    "category": "Role-Playing Games (RPGs)",
    "platform": "PC / PS5 / Xbox",
    "genre": "Role-Playing Games (RPGs)",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 35000,
    "original": 50000,
    "rating": 4.8,
    "color": "#6d28d9",
    "tag": "Available",
    "image": "assets/images/game-08.jpg"
  },
  {
    "id": 9,
    "title": "The Elder Scrolls V: Skyrim",
    "category": "Role-Playing Games (RPGs)",
    "platform": "PC / PS4 / Xbox / Switch",
    "genre": "Role-Playing Games (RPGs)",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 15000,
    "original": 28000,
    "rating": 4.9,
    "color": "#475569",
    "tag": "Available",
    "image": "assets/images/game-09.jpg"
  },
  {
    "id": 10,
    "title": "Persona 5 Royal",
    "category": "Role-Playing Games (RPGs)",
    "platform": "PC / PS4 / PS5 / Xbox / Switch",
    "genre": "Role-Playing Games (RPGs)",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 22000,
    "original": 36000,
    "rating": 4.5,
    "color": "#be123c",
    "tag": "Available",
    "image": "assets/images/game-10.jpg"
  },
  {
    "id": 11,
    "title": "Mass Effect 2",
    "category": "Role-Playing Games (RPGs)",
    "platform": "PC / PS3 / Xbox",
    "genre": "Role-Playing Games (RPGs)",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 12000,
    "original": 22000,
    "rating": 4.6,
    "color": "#1d4ed8",
    "tag": "Available",
    "image": "assets/images/game-11.jpg"
  },
  {
    "id": 12,
    "title": "Doom Eternal",
    "category": "Shooters",
    "platform": "PC / PS4 / PS5 / Xbox / Switch",
    "genre": "Shooters",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 18000,
    "original": 30000,
    "rating": 4.7,
    "color": "#dc2626",
    "tag": "Available",
    "image": "assets/images/game-12.jpg"
  },
  {
    "id": 13,
    "title": "Halo: Combat Evolved",
    "category": "Shooters",
    "platform": "PC / Xbox",
    "genre": "Shooters",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 10000,
    "original": 20000,
    "rating": 4.8,
    "color": "#1e3a8a",
    "tag": "Available",
    "image": "assets/images/game-13.jpg"
  },
  {
    "id": 14,
    "title": "Half-Life 2",
    "category": "Shooters",
    "platform": "PC",
    "genre": "Shooters",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 9000,
    "original": 18000,
    "rating": 4.9,
    "color": "#64748b",
    "tag": "Available",
    "image": "assets/images/game-14.jpg"
  },
  {
    "id": 15,
    "title": "BioShock",
    "category": "Shooters",
    "platform": "PC / PS4 / Xbox / Switch",
    "genre": "Shooters",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 14000,
    "original": 25000,
    "rating": 4.5,
    "color": "#075985",
    "tag": "Available",
    "image": "assets/images/game-15.jpg"
  },
  {
    "id": 16,
    "title": "Minecraft",
    "category": "Platformers, Strategy, & Simulation",
    "platform": "PC / PS4 / Xbox / Switch",
    "genre": "Platformers, Strategy, & Simulation",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 20000,
    "original": 35000,
    "rating": 4.6,
    "color": "#16a34a",
    "tag": "Available",
    "image": "assets/images/game-16.jpg"
  },
  {
    "id": 17,
    "title": "Portal 2",
    "category": "Platformers, Strategy, & Simulation",
    "platform": "PC / PS3 / Xbox",
    "genre": "Platformers, Strategy, & Simulation",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 10000,
    "original": 19000,
    "rating": 4.7,
    "color": "#0f766e",
    "tag": "Available",
    "image": "assets/images/game-17.jpg"
  },
  {
    "id": 18,
    "title": "Super Mario Odyssey",
    "category": "Platformers, Strategy, & Simulation",
    "platform": "Nintendo Switch",
    "genre": "Platformers, Strategy, & Simulation",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 28000,
    "original": 45000,
    "rating": 4.8,
    "color": "#e11d48",
    "tag": "Available",
    "image": "assets/images/game-18.jpg"
  },
  {
    "id": 19,
    "title": "Hades",
    "category": "Platformers, Strategy, & Simulation",
    "platform": "PC / PS4 / PS5 / Xbox / Switch",
    "genre": "Platformers, Strategy, & Simulation",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 16000,
    "original": 28000,
    "rating": 4.9,
    "color": "#9333ea",
    "tag": "Available",
    "image": "assets/images/game-19.jpg"
  },
  {
    "id": 20,
    "title": "Stardew Valley",
    "category": "Platformers, Strategy, & Simulation",
    "platform": "PC / PS4 / Xbox / Switch",
    "genre": "Platformers, Strategy, & Simulation",
    "condition": "Pre-owned • Very Good",
    "seller": "CTRL S Store",
    "price": 12000,
    "original": 22000,
    "rating": 4.5,
    "color": "#65a30d",
    "tag": "Available",
    "image": "assets/images/game-20.jpg"
  }
];
